#!/bin/bash

BORDER="#00ffffff"
SEPARATOR="#00ffffff"
FOREGROUND="#D8DEE9"
BACKGROUND="#E02E3440"
BACKGROUND_ALT="#00ffffff"
HIGHLIGHT_BACKGROUND="#3088C0D0"
HIGHLIGHT_FOREGROUND="#FFFFFF"

BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#fdd835"
BLUE="#1e88e5"
MAGENTA="#00897b"
CYAN="#00acc1"
PINK="#d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"

rofi -no-lazy-grab -modi drun -show drun \
-display-drun "Apps :" -drun-display-format "{name}" \
-hide-scrollbar true \
-sort \
-bw 0 \
-lines 11 \
-line-padding 8 \
-padding 20 \
-width 100% \
-eh 1 \
-xoffset 0 -yoffset 80 \
-location 2 \
-columns 2 \
-show-icons -icon-theme "Papirus" \
-font "Droid Sans Regular 30" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-me-select-entry '' \
-me-accept-entry 'MousePrimary' \

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
