#!/bin/bash

poweroff="襤"
reboot="勒"
lock=""
logout=""
screenshot=""

options="$poweroff\n$reboot\n$lock\n$screenshot"
chosen="$(echo -e $options | rofi -dmenu -theme ~/.config/rofi/style.rasi)"

case $chosen in
	$poweroff)
		sudo poweroff
	;;
	$reboot)
		sudo halt
	;;
	$lock)
		python3 lock.py
	;;
	$screenshot)
		scrot ~/pictures/screenshots/%Y-%m-%d-%T.png &
	;;
esac
